
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 15 13:41:46 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 38;
  public static final int CONST = 3;
  public static final int EQUALS = 37;
  public static final int GRTEQ = 32;
  public static final int QUESTIONMARK = 49;
  public static final int NUMCONST = 22;
  public static final int CASE = 11;
  public static final int NOTEQUAL = 30;
  public static final int LPAREN = 43;
  public static final int GREATER = 31;
  public static final int CONTINUE = 13;
  public static final int DECREMENT = 39;
  public static final int MINUS = 25;
  public static final int RPAREN = 44;
  public static final int LSSEQ = 34;
  public static final int SEMICOLON = 40;
  public static final int AND = 35;
  public static final int OR = 36;
  public static final int COMMA = 41;
  public static final int CLASS = 4;
  public static final int DIV = 27;
  public static final int LESSER = 33;
  public static final int PLUS = 24;
  public static final int IF = 6;
  public static final int DOT = 42;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 29;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 26;
  public static final int MOD = 28;
  public static final int LSQBRACKET = 47;
  public static final int BREAK = 12;
  public static final int VOID = 19;
  public static final int SWITCH = 10;
  public static final int COLON = 50;
  public static final int LBRACE = 45;
  public static final int ELSE = 7;
  public static final int ENUM = 18;
  public static final int READ = 15;
  public static final int CHARCONST = 23;
  public static final int WHILE = 9;
  public static final int RBRACE = 46;
  public static final int BOOLCONST = 21;
  public static final int EXTENDS = 5;
  public static final int RSQBRACKET = 48;
  public static final int PRINT = 16;
  public static final int DO = 8;
  public static final int IDENTIFIER = 20;
}

